### ISSUE TITLE
RAM not scaling

### ISSUE THREAD

**Issue by antonymayi** [dmlc/wormhole#55]
Seems xgboost job needs more then double amount of RAM on _each_ yarn NM then it needs (on single) host when running natively (no wormhole). That's not helping with scaling. Is there anything wrong with my config?

Example:
* SVM dataset of ~35M rows, 5.5GB in size
* using following xgboost config:
```
colsample_bytree = 0.836855129273
max_delta_step = 0.0
min_child_weight = 8
subsample = 0.813015161805
eta = 0.177476177765
model_out = "/tmp/xgbtest.dat"
num_round = 94
data = "/tmp/xgbtest.svm"
max_depth = 13
gamma = 0.0
```
* result:
  * on 6 node YARN - 27.5GB on _each_ node (so 6 * 27.5GB = 165GB taken!)
  * local mode - just 11GB

**Comment by tqchen** [comment]
You will want to add hdfs prefix to the path, so the xgboost is aware of the data is from hdfs and do splits when it reads in the data

**Comment by antonymayi** [comment]
sorry for confusing, that config example was only for the local mode. for yarn mode I am using data from hdfs and the config of course has the hdfs:// prefixes then. so this is not a problem.

**Comment by antonymayi** [comment]
config used for YARN mode:
```
colsample_bytree = 0.836855129273
max_delta_step = 0.0
min_child_weight = 8
subsample = 0.813015161805
eta = 0.177476177765
model_out = "hdfs:///tmp/xgbtest.dat"
num_round = 94
data = "hdfs:///tmp/xgbtest.svm"
max_depth = 13
gamma = 0.0
```

**Comment by antonymayi** [comment]
what is the expected memory footprint on a each cluster node? shouldn't it be 1/N compared to local mode?

**Comment by tqchen** [comment]
yes, normally it is 1/N, there could be exception if you have a lot of columns(i.e. sparse data)

**Comment by tqchen** [comment]
It also depends on what is shown, as the info shows on yarn console is the memory required from the submission script instead of actual ram used, you can ask for less ram during submission

**Comment by antonymayi** [comment]
yarn log shows also the actual usage (if either pmem or vmem checking is enabled):
```
2015-12-31 10:48:23,019 INFO ...: 49.4 GB of 52 GB physical memory used; 53.0 GB of 109.2 GB virtual memory used
```
plus I can confirm the same checking the actual xgboost process running within the containers:
```
$ pidstat -r -p 11586
10:50:54 AM       PID  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
10:50:54 AM     11586     51.61      0.00 55706200 52210392  19.79  xgboost.dmlc
```

...that's for a ~11GB SVM file -> 6 * 50GB (while in local mode it is 1 * 22GB)

**Comment by tqchen** [comment]
How many columns does your data have? The only reason I can expect this really to happen is due to large number of columns and bad synchronization and the program is optimized for continuous statistics(dense columns with a few categorical features). 

On the experiments I ran so far, it scales with 1/n with more 200G scale dataset

**Comment by antonymayi** [comment]
yes, my dataset is quite sparse:
rows: 66M
columns: 400k
average number of non-zero columns per line: 14

why is the local mode not affected by the sparsity?

also although off-topic given this subject (RAM) it is not only the memory but also the whole processing time being much worse (ie 5-times slower) on cluster vs local mode (with same amount of (combined) cores).

**Comment by tqchen** [comment]
both processing are optimized for sparse dataset, so xgboost can process very sparse dataset.
However, the communication pattern is not optimized for very sparse data(which affects memory and computation). This is the main reason why distributed mode could be slow. This can be alleviated by throwing more data into a single process, i.e. use multiple cores in each worker and enable multi-threading to maximum utilize the resources.

The communication pattern is not optimized for sparse data mainly because trees works well for dense dataset with continuous features, or categorical features with thousands level columns. For sparse indicator features, some histogram transformation might be needed for better performance

**Comment by antonymayi** [comment]
Thx for explanation.

I tried some benchmarking for different distribution patterns interested to see the effect of throwing more data into single process. In all cases using same SVM dataset of 7.4GB.

 Mode | #nodes | #cores/node | pmem/node | pmem combined
---------|------------|------------------|-----------------|----------------
 local   | 1           |  -                  | -                   | 15GB
YARN | 6           | 4                   | 39GB          | 234GB
YARN | 3           | 8                   | 73GB          | 219GB
YARN | 2           | 12                 | 106GB        | 212GB
YARN | 1           | 24                 | 207GB        | 207GB

So yes, the footprint is better when running on fewer nodes but the difference is marginal. Most interesting is the comparison of single node YARN cluster (so essentially single process) vs local mode - 207GB vs 15GB!

Could there be anything wrong just with my setup or is this still explainable by the synchronization design?

**Comment by tqchen** [comment]
Yes, this was due to the algorithm used in the distributed setting, which synchronizes the histograms on all branches, this was a huge cost and can cause the effect you mentioned here. So this was indeed an defect of the distributed version.

However, as mentioned in last post, xgboost works better on dense continuous data. For sparse indicator features, some histogram transformation might be needed for better accuracy, and speed as well
